name: Bluesky Organization Search

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight
  workflow_dispatch:  # Allow manual triggering

permissions:
    contents: write  # Add explicit permission to write to repository  

jobs:
  bsky_search:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use Github token for authentication

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install atproto

    - name: Run Bluesky search
      env:
        BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
        BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
      run: |
        python bluesky-org-search.py

    # Commit the report to the repository
    - name: Commit report to repository
      if: always()
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add "${{ env.REPORT_DIR }}/*"
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add search results for $(date +'%Y-%m-%d')"
          git push origin HEAD:${GITHUB_REF}
        fi

    # Upload the report as an artifact
    - name: Upload search results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: search-results
        path: ${{ env.REPORT_DIR }}
